### ISSUE TITLE
Do you support new line?

### ISSUE THREAD

**Issue by kingleuther** [Vashnak/react-toasts#2]
ToastStore.error('Hey, it worked ! \n kidding! there was an error');

please take note of the "\n"

**Comment by Vashnak** [comment]
Hi kingleuther, I will take a look this morning

**Comment by kingleuther** [comment]
@Vashnak, thanks! I've been looking for react-toast that will support "\n",

**Comment by Vashnak** [comment]
Hey, version 2.0.7 should now support it, you can upgrade your package.json and enjoy this feature ^^

**Comment by Vashnak** [comment]
Mmhhh I see, I need to add a class on toasts, I do that now

**Comment by kingleuther** [comment]
Thank you @Vashnak. Can i have your email? lets talk via the email.

**Comment by Vashnak** [comment]
Test

Le jeu. 5 juil. 2018 à 09:37, Leuther Mojica <notifications@github.com> a
écrit :

**Comment by Vashnak** [comment]
anthony.sarais@gmail.com (I'll delete this message after your mail)

**Comment by kingleuther** [comment]
@Vashnak  replied! tell me if you're done with the class :D

**Comment by Vashnak** [comment]
Yes, done

**Comment by kingleuther** [comment]
How to? :D

**Comment by Vashnak** [comment]
Feature Added.
