### ISSUE TITLE
Add translation to notification text

### ISSUE THREAD

**Issue by IrtazaHussain1** [Vashnak/react-toasts#20]
Hi, I am using the react-i18next library for translation. is there any way I can apply a translation to the notifications?. if any please guide me it will help me a lot. Thanks

**Comment by Vashnak** [comment]
I'm sorry for the very late response, but I suppose you could just call the notification function with the translated text ? 

Something like this `ToastsService.succes(t('notification:success_notification'))`

**Comment by IrtazaHussain1** [comment]
thanks, a lot man this really helped me.

**Comment by Vashnak** [comment]
Happy to help you, and sorry again for the very late response
