### ISSUE TITLE
Style issue when using bootstrap 

### ISSUE THREAD

**Issue by abdullahjavaid86** [Vashnak/react-toasts#21]
When I use bootstrap 4 in my application the default styles of notification messed up. Please guide me if I am doing something wrong or help me with custom styles.
Screenshot attached.

![Screenshot (3)](https://user-images.githubusercontent.com/31802757/95835601-dd3cd780-0d57-11eb-923a-bdce4bd91b90.png)

**Comment by abdullahjavaid86** [comment]
solved the issue by overriding display flex to block of toast-container

**Comment by crscaballero** [comment]
I've got the same situation once I've updated my `react` packages, I did the same to fix it, but I still consider that this should be open until be solved by its own package
