### ISSUE TITLE
PropTypes -> propTypes in new React

### ISSUE THREAD

**Issue by roy-k** [Vashnak/react-toasts#3]
hi;

```javascript
Container.PropTypes = {
    store: _propTypes2.default.object.required,
    position: _propTypes2.default.string
};
```

This get an waring in console at new react version;

see also [[React 16.2] Warning: Component Menu declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?](https://github.com/ericgio/react-bootstrap-typeahead/issues/274)

**Comment by roy-k** [comment]
I edit it at my local file, and warning still on. Seems like there is same code at dependencies, case i comment it and solve it.

**Comment by kasongoyo** [comment]
@roy-k I have submitted a pull request with the fix of this issue. I am now waiting for the owner to merge it and that's all

**Comment by Vashnak** [comment]
Merged, thank you guys
