### ISSUE TITLE
html contents in message support??

### ISSUE THREAD

**Issue by btechgroup** [Vashnak/react-toasts#7]
Does it support html contents in message?

**Comment by Vashnak** [comment]
Hello, Atm no, but if you need the feature, I can implement it today

**Comment by btechgroup** [comment]
that would be great if it supports custom links/buttons and heading elements

**Comment by Vashnak** [comment]
I will think about it, it could be effectively useful

**Comment by Vashnak** [comment]
You can now insert html element instead of string in the version 3 or upper.
You can you use it this way:
`const myHtml = <div>My content</div>;`
`ToastsStore.info(myHtml);`
